### PR TITLE
(RE-10177) Use packaging as a gem

### PR DESCRIPTION
**Pull request by mwaggett**

### CODE REVIEW

**Comment by mwaggett** [comment]
This PR was prompted when I noticed that some of the education vm jobs on jenkins-compose (which are honestly probably obsolete) use katamari in order to make use of packaging tasks.
I'm not sure what else might use katamari, so I'm not sure how to really test this PR, but I figured it would be a good thing to have, just in case.

**Review by e-gris — APPROVED** [review]

**Comment by sarameisburger** [comment]
Will this change prevent a local user from testing their packaging branch? We're removing the call to packaging_url in the rakefile

**Comment by mwaggett** [comment]
@sarameisburger setting the `PACKAGING_LOCATION` environment variable should continue to allow people to use dev branches of packaging

**Comment by sarameisburger** [comment]
Ok, so then we can remove the references to packing in the build_defaults file and will probs wanna update the README

**Comment by mwaggett** [comment]
@sarameisburger updated!

**Review by underscorgan — APPROVED** [review]

**Review by sarameisburger — APPROVED** [review]

**Pull request merged**
